name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do seu código
      - uses: actions/checkout@v3

      # 2. Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instala dependências
      - name: Install dependencies
        run: npm ci

      # 4. Build do Vue (injeta as variáveis de ambiente)
      - name: Build
        env:
          VUE_APP_API_KEY: ${{ secrets.VUE_APP_API_KEY }}
          VUE_APP_AUTH_DOMAIN: ${{ secrets.VUE_APP_AUTH_DOMAIN }}
          VUE_APP_PROJECT_ID: ${{ secrets.VUE_APP_PROJECT_ID }}
          VUE_APP_STORAGE_BUCKET: ${{ secrets.VUE_APP_STORAGE_BUCKET }}
          VUE_APP_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_MESSAGING_SENDER_ID }}
          VUE_APP_APP_ID: ${{ secrets.VUE_APP_APP_ID }}
          VUE_APP_MEASUREMENT_ID: ${{ secrets.VUE_APP_MEASUREMENT_ID }}
        run: npm run build

      # 5. Publica o conteúdo de ./dist no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
